type LooseRow = {
  id?: string;
  user_id?: string;
  member_id?: string;
  host_member_id?: string | null;
  full_name?: string;
  company_name?: string | null;
  purpose_of_visit?: string;
  role?: string;
  email?: string | null;
  phone?: string | null;
  department?: string | null;
  hourly_rate?: number | string | null;
  gender?: string | null;
  type?: string;
  status?: string;
  start_date?: string;
  end_date?: string;
  created_at?: string;
  updated_at?: string;
  timestamp?: string;
  punch_in?: string;
  punch_out?: string | null;
  clockIn?: string;
  clockOut?: string | null;
  minutes?: number;
  hours?: number;
  location_name?: string | null;
  locationName?: string | null;
  note?: string | null;
  reason?: string | null;
  actorLabel?: string | null;
  personType?: string;
  personName?: string | null;
  source?: string;
  name?: string;
  label?: string;
  day?: string;
  month?: string;
  value?: number;
  fill?: string;
  face_reference?: unknown;
  face_enrolled?: boolean | null;
  faceEnrollment?: import("./index").FaceEnrollment | null;
  employee_id?: string | null;
  employment_type?: string | null;
  address?: string | null;
  date_of_birth?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  notes?: string | null;
  created_by?: string | null;
  members?: LooseRow | LooseRow[] | null;
  host_member?: { full_name?: string | null } | { full_name?: string | null }[] | null;
  capturedIn?: import("../lib/timeRecords").CaptureDetails | null;
  capturedOut?: import("../lib/timeRecords").CaptureDetails | null;
  [key: string]: unknown;
};
