import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { writeAuditLog } from "../lib/audit";

type Device = { id: string; device_id: string; name: string; device_type: string; status: string; last_seen_at: string | null };
type Audit = { id: string; action: string; entity_type: string; created_at: string };
type License = { id: string; plan: string; status: string; expires_at: string | null; max_devices: number };

export default function AdminControlsPage() {
  const [devices, setDevices] = useState<Device[]>([]); const [audits, setAudits] = useState<Audit[]>([]); const [licenses, setLicenses] = useState<License[]>([]); const [error, setError] = useState("");
  async function load() { const [d, a, l] = await Promise.all([supabase.from("registered_devices").select("id,device_id,name,device_type,status,last_seen_at").order("last_seen_at", { ascending: false }), supabase.from("audit_logs").select("id,action,entity_type,created_at").order("created_at", { ascending: false }).limit(25), 
    supabase.from("licenses").select("id,plan,status,expires_at,max_devices").order("created_at", { ascending: false })]); if (d.error || a.error || l.error) setError((d.error || a.error || l.error)?.message || "Unable to load controls."); setDevices((d.data || []) as Device[]); setAudits((a.data || []) as Audit[]); setLicenses((l.data || []) as License[]); }
  useEffect(() => { void load(); }, []);
  async function setDeviceStatus(device: Device, status: "active" | "revoked") { const { error: updateError } = await supabase.from("registered_devices").update({ status }).eq("id", device.id); if (updateError) setError(updateError.message); else { await writeAuditLog(`device_${status}`, "device", device.id); void load(); } }
  async function setLicenseStatus(license: License, status: "active" | "suspended") { const { error: updateError } = await supabase.from("licenses").update({ status }).eq("id", license.id); if (updateError) setError(updateError.message); else { await writeAuditLog(`license_${status}`, "license", license.id); void load(); } }
  return <div className="space-y-6"><div><p className="text-xs uppercase tracking-[0.2em] text-primary">Administrator controls</p><h1 className="font-display text-2xl font-bold text-ink mt-2">Devices & audit trail</h1><p className="text-sm text-ink-muted mt-1">Revoke lost tablets and review security-sensitive activity.</p></div>{
    error && <p className="text-danger text-sm">{error}</p>}<section className="card p-5"><h2 className="font-semibold text-ink mb-4">Registered devices</h2><div className="space-y-3">{devices.map((device) => <div key={device.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-3"><div>
      <p className="font-medium text-ink">{device.name}</p><p className="text-xs text-ink-muted">{device.device_type} · {device.device_id.slice(0, 8)} · {device.status}</p></div><button className="btn-secondary text-xs" onClick={() => void setDeviceStatus(device, device.status === "revoked" ? "active" : "revoked")}>{device.status === "revoked" ? "Restore" : "Revoke"}</button></div>)}
      {!devices.length && <p className="text-sm text-ink-muted">No devices registered yet.</p>}</div></section><section className="card p-5"><h2 className="font-semibold text-ink mb-4">Recent audit events</h2><div className="space-y-2">{audits.map((audit) => <div key={audit.id} className="flex justify-between gap-4 border-b border-border py-2 text-sm"><span className="text-ink">{audit.action} · {audit.entity_type}</span><span className="text-ink-muted text-xs">{new Date(audit.created_at).toLocaleString()}</span></div>)}</div></section></div>;
  return <div className="space-y-6"><div><p className="text-xs uppercase tracking-[0.2em] text-primary">Administrator controls</p><h1 className="font-display text-2xl font-bold text-ink mt-2">Devices, licenses & audit trail</h1><p className="text-sm text-ink-muted mt-1">Revoke lost tablets, suspend subscriptions, and review security-sensitive activity.
  </p></div>{error && <p className="text-danger text-sm">{error}</p>}<section className="card p-5"><h2 className="font-semibold text-ink mb-4">Registered devices</h2><div className="space-y-3">{devices.map((device) => <div key={device.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-3"><div>
    <p className="font-medium text-ink">{device.name}</p><p className="text-xs text-ink-muted">{device.device_type} · {device.device_id.slice(0, 8)} · {device.status}</p></div><button className="btn-secondary text-xs" onClick={() => void setDeviceStatus(device, device.status === "revoked" ? "active" : "revoked")}>{device.status === "revoked" ? "Restore" : "Revoke"}
      </button></div>)}{!devices.length && <p className="text-sm text-ink-muted">No devices registered yet.</p>}</div></section><section className="card p-5"><h2 className="font-semibold text-ink mb-4">Licenses</h2><div className="space-y-3">{licenses.map((license) => <div key={license.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-3"><div><p className="font-medium text-ink">{license.plan} · {license.status}</p><p className="text-xs text-ink-muted">Up to {license.max_devices} devices{license.expires_at ? ` · Expires ${new Date(license.expires_at).toLocaleDateString()}` : " · No expiry"}</p></div><button className="btn-secondary text-xs" onClick={() => void setLicenseStatus(license, license.status === "suspended" ? "active" : "suspended")}>{license.status === "suspended" ? "Resume" : "Suspend"}</button></div>)}{!licenses.length && <p className="text-sm text-ink-muted">No licenses found.</p>}</div></section><section className="card p-5"><h2 className="font-semibold text-ink mb-4">Recent audit events</h2><div className="space-y-2">{audits.map((audit) => <div key={audit.id} className="flex justify-between gap-4 border-b border-border py-2 text-sm"><span className="text-ink">{audit.action} · {audit.entity_type}</span><span className="text-ink-muted text-xs">{new Date(audit.created_at).toLocaleString()}</span></div>)}</div></section></div>;
}
