import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { getWeekStart, type EmployeeSchedule, type ShiftType } from "../lib/shiftSchedule";

type Employee = { id: string; full_name: string | null; department: string | null; kind: "employee" | "member" };
const DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export default function SchedulesPage() {
  const [employees, setEmployees] = useState<Employee[]>([]); const [selected, setSelected] = useState<Employee | null>(null); const [weekStart, setWeekStart] = useState(getWeekStart()); const [rows, setRows] = useState<EmployeeSchedule[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { void Promise.all([supabase.from("profiles").select("id,full_name,department"), supabase.from("members").select("id,full_name,department")]).then(([staff, members]) => setEmployees([...(staff.data || []).map((row) => ({ ...row, kind: "employee" as const })), ...(members.data || []).map((row) => ({ ...row, kind: "member" as const }))] as Employee[])); }, []);
  useEffect(() => { if (!selected) return; const subjectColumn = selected.kind === "member" ? "member_id" : "user_id"; void supabase.from("employee_schedules").select("id,user_id,member_id,week_start,weekday,shift_type,start_time,end_time").eq(subjectColumn, selected.id).eq("week_start", weekStart).then(({ data }) => { const existing = new Map((data || []).map((row) => [row.weekday, row as EmployeeSchedule])); setRows(DAYS.map((_, weekday) => existing.get(weekday) || { user_id: selected.kind === "employee" ? selected.id : null, member_id: selected.kind === "member" ? selected.id : null, week_start: weekStart, weekday, shift_type: "morning", start_time: "00:00", end_time: "23:59" })); }); }, [selected, weekStart]);
  function update(weekday: number, shift_type: ShiftType) { setRows((current) => current.map((row) => row.weekday === weekday ? { ...row, shift_type, start_time: shift_type === "evening" ? "18:00" : "00:00", end_time: shift_type === "evening" ? "12:00" : "23:59" } : row)); }
  async function save() { if (!selected) return; setMessage(""); const { error } = await supabase.from("employee_schedules").upsert(rows.map(({ id: _id, ...row }) => row), { onConflict: selected.kind === "member" ? "member_id,week_start,weekday" : "user_id,week_start,weekday" }); setMessage(error ? error.message : "Weekly schedule saved."); }
  return <div className="space-y-6"><div><p className="text-xs uppercase tracking-[0.2em] text-primary">Attendance planning</p><h1 className="font-display text-2xl font-bold text-ink mt-2">Weekly schedules</h1><p className="text-sm text-ink-muted mt-1">Assign a different schedule for every employee or member and every week.</p></div><section className="card p-5 space-y-5"><div className="grid gap-3 sm:grid-cols-2"><select className="input" value={selected?.id || ""} onChange={(event) => setSelected(employees.find((employee) => employee.id === event.target.value) || null)}><option value="">Select employee or member</option>{employees.map((employee) => <option key={`${employee.kind}-${employee.id}`} value={employee.id}>{employee.full_name || "Unnamed"} · {employee.kind}</option>)}</select><input type="date" className="input" value={weekStart} onChange={(event) => setWeekStart(getWeekStart(new Date(`${event.target.value}T12:00:00`)))} /></div>{selected && <div className="space-y-3"><p className="text-sm text-ink-muted">Week starting {weekStart}</p>{rows.map((row) => <div key={row.weekday} className="grid grid-cols-[1fr_140px] items-center gap-3 border-b border-border py-3"><span className="text-sm font-medium text-ink">{DAYS[row.weekday]}</span><select className="input" value={row.shift_type} onChange={(event) => update(row.weekday, event.target.value as ShiftType)}><option value="morning">Morning</option><option value="evening">Evening</option><option value="off">Off</option></select></div>)}<button className="btn-primary" onClick={() => void save()}>Save weekly schedule</button>{message && <p className="text-sm text-primary">{message}</p>}</div>}</section></div>;
}
